### ISSUE TITLE
In DMX-Controls tab the range of channels invalid inputs not updating correctly

### ISSUE THREAD

**Issue by ethanpartida** [teslaworksumn/lightshow-Gallium#124] opened 2019-11-01 21:12 UTC

**Comment by ethanpartida** [comment] 2019-11-01 21:17
![incorrectError](https://user-images.githubusercontent.com/42383664/68057137-09845300-fcc3-11e9-8374-58eb321640f4.png)

**Comment by theeldestelder** [comment] 2019-11-05 21:30
Do you have steps to reproduce this? Not really a big deal for this issue but I am curious how you managed to do that because I've been trying locally and can't get it to happen.

**Comment by ethanpartida** [comment] 2019-11-05 22:35
Yes, try inputting 3-2 for the range of inputs. Both boxes will go red. Then change the 1-3 and submit. Only the 1 will change colors not the two. (The two changes if you edit it at all though)

On Nov 5, 2019 3:30 PM, theeldestelder <notifications@github.com> wrote:

Do you have steps to reproduce this? Not really a big deal for this issue but I am curious how you managed to do that because I've been trying locally and can't get it to happen.

**Comment by theeldestelder** [comment] 2019-11-11 20:50
Closed by #125

**Closed by theeldestelder** 2019-11-11 20:50 UTC
Labels: bug
